_target_: hvae.models.DCTHVAE
img_size: ${dataset.img_size}
in_channels: ${dataset.num_channels}
channels: [16, 32, 32, 64]
latent_dim: 16
beta: 0.5
num_levels: 2
ks: [64, 16]
lr: 0.001
residual: false
num_classes: ${dataset.num_classes}