defaults:
 - _self_
 - dataset: cifar10
 - model: vae

training:
  max_epochs: 100
  batch_size: 256
  num_workers: 16
  lr: 0.001

wandb:
  project: hvae
  dir: wandb
  group: null
  mode: online
  log_every_n_steps: 10