defaults:
 - _self_
 - dataset: cifar10
 - model: vae

trainer:
  _target_: lightning.pytorch.Trainer
  accelerator: auto
  default_root: ${oc.env:WORK}/projects/hvae/lightning
  devices: 1
  enable_checkpointing: false
  enable_progress_bar: false
  log_every_n_steps: 10
  logger: ${wandb}
  max_epochs: 100

training:
  batch_size: 256
  num_workers: 8
  lr: 0.001

wandb:
  _target_: lightning.pytorch.loggers.WandbLogger
  project: hvae
  save_dir: ${oc.env:WORK}/projects/hvae/wandb
  group: null
  mode: online